// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: 2-multi-inserts.sql

package dbsqlc

import (
	"context"
)

const insertTaskAssociatedData = `-- name: InsertTaskAssociatedData :exec
INSERT INTO task_associated_data (task_id, top_level_fields)
VALUES ($1, extract_top_level_fields($2))
`

type InsertTaskAssociatedDataParams struct {
	TaskID   int64  `json:"task_id"`
	ArgsJson []byte `json:"args_json"`
}

func (q *Queries) InsertTaskAssociatedData(ctx context.Context, db DBTX, arg InsertTaskAssociatedDataParams) error {
	_, err := db.Exec(ctx, insertTaskAssociatedData, arg.TaskID, arg.ArgsJson)
	return err
}
