// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID             int64              `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Args           []byte             `json:"args"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
}

type TaskAssociatedDatum struct {
	TaskID         int64    `json:"task_id"`
	TopLevelFields []string `json:"top_level_fields"`
}
